> Configure project :app WARNING: Using flatDir should be avoided because it doesn't support any meta-data formats.
> Configure project :capacitor-cordova-android-plugins
WARNING: Using flatDir should be avoided because it doesn't support any meta-data formats.

> Task :app:processDebugMainManifest
package="com.theroom.app" found in source AndroidManifest.xml: C:\ProyektoCS\TheRoom\android\app\src\main\AndroidManifest.xml.
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported, and the value is ignored.
Recommendation: remove package="com.theroom.app" from the source AndroidManifest.xml: C:\ProyektoCS\TheRoom\android\app\src\main\AndroidManifest.xml.

> Task :app:compileDebugJavaWithJavac FAILED
C:\ProyektoCS\TheRoom\android\app\src\main\java\com\theroom\app\MainActivity.java:5: error: package com.codetrixstudio.capacitor.GoogleAuth does not exist
import com.codetrixstudio.capacitor.GoogleAuth.GoogleAuth;
                                              ^
C:\ProyektoCS\TheRoom\android\app\src\main\java\com\theroom\app\MainActivity.java:13: error: cannot find symbol
        registerPlugin(GoogleAuth.class);
                       ^
  symbol:   class GoogleAuth
  location: class MainActivity
2 errors

[Incubating] Problems report is available at: file:///C:/ProyektoCS/TheRoom/android/build/reports/problems/problems-report.html

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler output below.
  C:\ProyektoCS\TheRoom\android\app\src\main\java\com\theroom\app\MainActivity.java:13: error: cannot find symbol
          registerPlugin(GoogleAuth.class);
                         ^
    symbol:   class GoogleAuth
    location: class MainActivity
  C:\ProyektoCS\TheRoom\android\app\src\main\java\com\theroom\app\MainActivity.java:5: error: package com.codetrixstudio.capacitor.GoogleAuth does not exist
  import com.codetrixstudio.capacitor.GoogleAuth.GoogleAuth;
                                                ^
  2 errors

* Try:
> Check your code and dependencies to fix the compilation error(s)
> Run with --scan to get full insights.

BUILD FAILED in 4s
181 actionable tasks: 95 executed, 86 up-to-date